export const GET_COUNTRIES_DATA_PENDING = "GET_COUNTRIES_DATA_PENDING";
export const GET_COUNTRIES_DATA_FULFILLED = "GET_COUNTRIES_DATA_FULFILLED";
export const GET_COUNTRIES_DATA_REJECTED = "GET_COUNTRIES_DATA_REJECTED";
export const RESET_COUNTRIES_DATA = "RESET_COUNTRIES_DATA";
